[package]
name = "cst92xx"
version = "0.1.0"
edition = "2024"
authors = ["Sebastian Almendra"]
license = "MIT"
repository = "https://github.com/ScripTerasu/cst92xx-touch-driver"
description = "Driver crate for CST92xx (CST9217 and CST9220) touch controllers with async and blocking embedded-hal support."
keywords = ["touchscreen", "cst92xx", "cst9217", "cst9220", "embedded-hal", "embedded-hal-async", "driver"]
categories = ["embedded", "hardware-support", "no-std"]
readme = "README.md"
exclude = ["docs/", ".*"]

[dependencies]
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
heapless = "0.8"
embassy-time = "0.5.1"
defmt = { version = "1.1.1", optional = true }

[features]
defmt = ["dep:defmt"]

[dev-dependencies]
futures = "0.3"
